### ISSUE TITLE
Error in 2.7.3 at flow:package:rescan

### ISSUE THREAD

**Issue by patriceckhart** [TYPO3/Fluid#691]
Version: 2.7.3

When I run the `flow flow:package:rescan` I get the following error. The error does not occur with version 2.7.2.

Error: 
Warning: Undefined variable $argv in /data/neos/Packages/Libraries/typo3fluid/fluid/src/Tools/console.php line 22

**Comment by fcool** [comment]
Sadly this is no bug in typo3fluid but a bug in Flow's Object-Management.

It seems like enabling the Object-Management for `typo3fluid` is not necessary at all. At least in one project I testet it was sufficient to disable it for `typo3fluid` like that in Flow's Settings.yaml:
```yaml
Neos:
  Flow:
    object:
      includeClasses:
        'typo3fluid.fluid': []
```
